### ISSUE TITLE
App crash after latest update (3.9.1) - Redmi Note 8T

### ISSUE THREAD

**Issue by ImintA2** [moezbhatti/qksms#1740]
My phone is Redmi Note 8T (MIUI Global 12.0.2 QCXMIXM)
After the latest update I cannot open the app anymore, also unable to receive SMS (no more notification).
My phone's default SMS app is still working fine.
I've tried reinstalling the app to no avail.

The crash report contains this information:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/R$string;
	at com.google.android.gms.common.internal.StringResourceValueReader.<init>(Unknown Source:4)
	at com.google.firebase.FirebaseOptions.fromResource(FirebaseOptions.java:156)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:242)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2117)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2091)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7191)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6674)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6569)
	at android.app.ActivityThread.access$1400(ActivityThread.java:226)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1889)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7564)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: com.google.android.gms.common.R$string
	... 18 more

**Comment by moezbhatti** [comment]
This should be fixed in 445d425144efde5ca6f0672cb6965f0c0245e5a5, I'm just waiting for more users to test it and confirm that it doesn't reopen #1712

**Comment by Kolossi** [comment]
I got update 8 hours ago labeled "27 Jan 2020" in play store and v3.9.1 in app info.

I'm now getting forceclose immediately on entry.

I'm posting here because I'm happy to test an updated version - UK EE carrier, Galaxy S20+ - if it helps @moezbhatti , please reply with instructions how to get the latest (on here should be ok as I'm subscribed to this thread).

Thanks for a great app and your working addressing the current issue.

**Comment by moezbhatti** [comment]
I would recommend reverting to 3.8.1 or 3.9.0 in the meantime - but I'm aiming to have 3.9.2 available this evening

**Comment by felixrono** [comment]
**replace with this new newer version of realm**

dependencies {

    classpath 'io.realm:realm-gradle-plugin:6.0.2'
}

**Comment by moezbhatti** [comment]
@felixrono unfortunately it turns out that upgrading Realm beyond `5.8.0` causes the performance issues described in #1712 

`5.8.0` is Incompatible with gradle build tools 3.6+ however, which is what caused this crash. I've had to downgrade the gradle build tools, and thus remove ViewBinding support in order to get it working without impacting the performance: 062adb76ac89d57bb73af75244f282a1a5dfa3d9

**Comment by felixrono** [comment]
Fair enough ...thanks

**Comment by moezbhatti** [comment]
Fixed in 062adb76ac89d57bb73af75244f282a1a5dfa3d9
