### ISSUE TITLE
Crash when opening conversation with VCard

### ISSUE THREAD

**Issue by lp35** [moezbhatti/qksms#1831]
Hi,

A contact just sent me a vcard that does not seems to have a "name" in it, resulting of a crash each time I'm trying to open the conversation.

Any help for this one?

Thanks!

### OBSERVATIONS
Log:

```
11-16 22:38:36.282  7533  7533 E AndroidRuntime: FATAL EXCEPTION: main
11-16 22:38:36.282  7533  7533 E AndroidRuntime: Process: com.moez.QKSMS, PID: 7533
11-16 22:38:36.282  7533  7533 E AndroidRuntime: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalStateException: vcard.formattedName must not be null
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.uber.rxdogtag.DogTagObserver.lambda$onNext$3$DogTagObserver(DogTagObserver.java:56)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.uber.rxdogtag.-$$Lambda$DogTagObserver$Bul2aJuZ0nriT_735invreaJZFw.run(Unknown Source:4)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.uber.rxdogtag.RxDogTag.guardedDelegateCall(RxDogTag.java:221)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.uber.rxdogtag.DogTagObserver.onNext(DogTagObserver.java:56)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: Caused by: java.lang.IllegalStateException: vcard.formattedName must not be null
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.moez.QKSMS.feature.compose.part.VCardBinder.bindPart(VCardBinder.kt:66)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at [[ Originating callback: onNext ]].(:0)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at [[ ↓↓ Original trace ↓↓ ]].(:0)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.moez.QKSMS.feature.compose.part.VCardBinder$bindPart$5.accept(VCardBinder.kt:66)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at com.moez.QKSMS.feature.compose.part.VCardBinder$bindPart$5.accept(VCardBinder.kt:42)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
11-16 22:38:36.282  7533  7533 E AndroidRuntime: 	... 14 more
11-16 22:38:36.284  1363  3457 W ActivityManager: Process com.moez.QKSMS has crashed too many times: killing!
```

**Comment by alireza1082** [comment]
this error also occurs when share a Vcard with a contact program

**Comment by dhjaber** [comment]
hi there ,,
 look when you send attache contact you should have MMS
APN   configured on your Device the MMS APN  info depending on your network provider
and then you should allow MMS   messaging on your sim card data
i think so

**Comment by ecspresso** [comment]
I have the same problem, mms apn configured. V3.9.2
