### ISSUE TITLE
App crashes when deleting scheduled message

### ISSUE THREAD

**Issue by SarmentoRE** [moezbhatti/qksms#1911]
### DESCRIPTION
App crashes when trying to delete scheduled message. Running graphene os

### STEPS
1. Schedule message to send
2. Go to schedule messages screen
3. Click on message and tap delete

### OBSERVATIONS
````
type: crash
osVersion: google/cheetah/cheetah:13/TQ1A.230105.002/2023011000:user/release-keys
package: com.moez.QKSMS:2220
process: com.moez.QKSMS
processUptime: 7741 + 276 ms

io.reactivex.exceptions.OnErrorNotImplementedException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
Caused by: io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
	at com.moez.QKSMS.feature.scheduled.ScheduledViewModel.bindView(ScheduledViewModel.kt:71)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at io.realm.BaseRealm.checkAllowWritesOnUiThread(BaseRealm.java:553)
	at io.realm.Realm.executeTransaction(Realm.java:1629)
	at com.moez.QKSMS.repository.ScheduledMessageRepositoryImpl.deleteScheduledMessage(ScheduledMessageRepositoryImpl.kt:72)
	at com.moez.QKSMS.feature.scheduled.ScheduledViewModel$bindView$$inlined$withLatestFrom$1.apply(Observables.kt:198)
	at io.reactivex.internal.operators.observable.ObservableWithLatestFrom$WithLatestFromObserver.onNext(ObservableWithLatestFrom.java:76)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
	at com.moez.QKSMS.common.MenuItemAdapter.onCreateViewHolder$lambda$8$lambda$7(MenuItemAdapter.kt:80)
	at com.moez.QKSMS.common.MenuItemAdapter.$r8$lambda$RH34JQv66UoAa-rn53rPXw-lQMY(Unknown Source:0)
	at com.moez.QKSMS.common.MenuItemAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29341)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

````

**Comment by TinySpins** [comment]
I have the same issue.
Running LineageOS 19.1 on OnePlus 5T.

**Comment by BicBoiSpyder** [comment]
I also have this issue running GrapheneOS build TQ1A.230205.002.2023021000 on a Google Pixel 6 Pro.

**Comment by ghw49** [comment]
Same problem Samsung Galaxy Fold 4. Work around - Scheduled message. Disable internet access. Force send scheduled message. Message not sent. Now delete unsent message

**Comment by konradmietelski** [comment]
Same issue on "clean" Android 13 on Nokia x10.

> Work around - Scheduled message. Disable internet access. Force send scheduled message. Message not sent. Now delete unsent message

Real live-saver in my case - I scheduled couple unwanted messaged by accident. I had to pull out SIM cards though before send.

**Comment by ghw49** [comment]
> Same issue on "clean" Android 13 on Nokia x10.
> 
> > Work around - Scheduled message. Disable internet access. Force send scheduled message. Message not sent. Now delete unsent message
> 
> Real live-saver in my case - I scheduled couple unwanted messaged by accident. I had to pull out SIM cards though before send.

Happy you able to delete; Sad because much more work

Work around (modified) - Scheduled message. Enter airplane mode. Force send scheduled message. Message not sent. Now delete unsent message. Exit airplane mode.

**Comment by turbodialup** [comment]
Same issue here. Google Pixel 7, GrapheneOS, Android 13, build TQ2A.230505.002.2023060700

**Comment by joseio** [comment]
In QKSMS get 3.10.1 this issue persists for me on grapheneos, unfortunately
