### ISSUE TITLE
[bug] app Force Closes when setting a conversation on silent.

### ISSUE THREAD

**Issue by pitman10** [moezbhatti/qksms#414]
Recorded the crash here: https://gfycat.com/MintyFineAdder

This happens to any conversation I try to set "Silent" to, and only Silent, any other kind of sound works.

Android version : 5.1.1 
Galaxy S6 (SM-G920F)

**Comment by pitman10** [comment]
Still happening on Marshmallow (6.0.1)

**Comment by moezbhatti** [comment]
Which QKSMS version are you using?

**Comment by AnAverageHuman** [comment]
This is still an issue on Android 6.0.1, QKSMS version 2.7.3 from F-Droid.

Logcat:

```
07-28 21:21:02.651  9443  9443 E AndroidRuntime: FATAL EXCEPTION: main
07-28 21:21:02.651  9443  9443 E AndroidRuntime: Process: com.moez.QKSMS, PID: 9443
07-28 21:21:02.651  9443  9443 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=716, result=-1, data=Intent { (has extras) }} to activity {com.moez.QKSMS/com.moez.QKSMS.ui.messagelist.MessageListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:4925)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4968)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.app.ActivityThread.access$1600(ActivityThread.java:222)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:158)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7229)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
07-28 21:21:02.651  9443  9443 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at com.moez.QKSMS.ui.messagelist.MessageListActivity.onActivityResult(MessageListActivity.java:149)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:7137)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
07-28 21:21:02.651  9443  9443 E AndroidRuntime:        ... 10 more
```

**Comment by moezbhatti** [comment]
The quick toggle has been removed in QKSMS 3.0
