### ISSUE TITLE
Automated mobile data enabling is broken since Lollipop

### ISSUE THREAD

**Issue by StephaneBausseron** [moezbhatti/qksms#598]
### DESCRIPTION
Since Lollipop, the automated mobile data is broken. So a MMS cannot be sent if data is disabled.

### STEPS
1. Take a mobile in Lollipop or Marshmallow
2. Install QKSMS and configure MMS settings
3. Send a MMS with mobile data enabled => send OK
4. Send a MMS with mobile data disabled => MMS is bloqued in "sending" state.

### EXPECTED
MMS shall be sent.

### OBSERVATIONS
The issue is due to a private method of the SDK (setMobileDataEnabled) which was removed in Lollipop.

See the backtrace:
08-18 10:39:50.002  4323  4720 D PhoneInterfaceManager: [PhoneIntfMgr] getDataEnabled: subId=1 phoneId=0
08-18 10:39:50.002 17767 18419 E Utils   : exception thrown
08-18 10:39:50.002 17767 18419 E Utils   : java.lang.NoSuchMethodException: setMobileDataEnabled [boolean]
08-18 10:39:50.002 17767 18419 E Utils   :      at java.lang.Class.getMethod(Class.java:630)
08-18 10:39:50.002 17767 18419 E Utils   :      at java.lang.Class.getDeclaredMethod(Class.java:589)
08-18 10:39:50.002 17767 18419 E Utils   :      at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
08-18 10:39:50.002 17767 18419 E Utils   :      at com.android.mms.transaction.TransactionService.onNewIntent(TransactionService.java:237)
08-18 10:39:50.002 17767 18419 E Utils   :      at com.android.mms.transaction.TransactionService$ServiceHandler.handleMessage(TransactionService.java:644)
08-18 10:39:50.002 17767 18419 E Utils   :      at android.os.Handler.dispatchMessage(Handler.java:102)
08-18 10:39:50.002 17767 18419 E Utils   :      at android.os.Looper.loop(Looper.java:148)
08-18 10:39:50.002 17767 18419 E Utils   :      at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by frogoscar** [comment]
http://stackoverflow.com/questions/26539445/the-setmobiledataenabled-method-is-no-longer-callable-as-of-android-l-and-later

**Comment by themelisx** [comment]
you have to be system app to do this
add this to manifest:  <uses-permission android:name="android.permission.MODIFY_PHONE_STATE"/>
replace function setMobileDataEnabled (at Utils.java) with this one:

public static void setMobileDataEnabled(Context context, boolean enabled) {

        if (Build.VERSION.SDK_INT >= 21) {
            try {
                TelephonyManager telephonyService = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
                Method setMobileDataEnabledMethod = telephonyService.getClass().getDeclaredMethod("setDataEnabled", boolean.class);
                if (null != setMobileDataEnabledMethod){
                    setMobileDataEnabledMethod.invoke(telephonyService, enabled);
                }
                return;
            }
            catch (Exception ex){
                return;
            }
        }
        else {
            try {
                final ConnectivityManager conman = (ConnectivityManager)  context.getSystemService(Context.CONNECTIVITY_SERVICE);
                final Class conmanClass = Class.forName(conman.getClass().getName());
                final Field iConnectivityManagerField = conmanClass.getDeclaredField("mService");
                iConnectivityManagerField.setAccessible(true);
                final Object iConnectivityManager = iConnectivityManagerField.get(conman);
                final Class iConnectivityManagerClass =  Class.forName(iConnectivityManager.getClass().getName());
                final Method setMobileDataEnabledMethod = iConnectivityManagerClass.getDeclaredMethod("setMobileDataEnabled", Boolean.TYPE);
                setMobileDataEnabledMethod.setAccessible(true);
                setMobileDataEnabledMethod.invoke(iConnectivityManager, enabled);
                return; 
            }
            catch (NoSuchMethodException e) {
                final ConnectivityManager conman = (ConnectivityManager)  context.getSystemService(Context.CONNECTIVITY_SERVICE);
                Class conmanClass;
                try {
                    conmanClass = Class.forName(conman.getClass().getName());
                    final Field iConnectivityManagerField = conmanClass.getDeclaredField("mService");
                    iConnectivityManagerField.setAccessible(true);
                    final Object iConnectivityManager = iConnectivityManagerField.get(conman);
                    final Class iConnectivityManagerClass =  Class.forName(iConnectivityManager.getClass().getName());
                    Class[] cArg = new Class[2];
                    cArg[0] = String.class;
                    cArg[1] = Boolean.TYPE;
                    Method setMobileDataEnabledMethod = iConnectivityManagerClass.getDeclaredMethod("setMobileDataEnabled", cArg);
                    Object[] pArg = new Object[2];
                    pArg[0] = context.getPackageName();
                    pArg[1] = enabled;
                    setMobileDataEnabledMethod.setAccessible(true);
                    setMobileDataEnabledMethod.invoke(iConnectivityManager, pArg);
                    return; 
                }
                catch (Exception e1) {
                    e1.printStackTrace();
                    return;
                }
            }
            catch (Exception e) {
                return;
            }
        }


    }
